// ulde/plugins/browser/ulde-mermaid-browser.plugin.ts

import { BrowserDomPlugin } from '../../core/host/ulde-browser-host';
import mermaid from 'mermaid';
import Panzoom from '@panzoom/panzoom'


let handler!: (event: WheelEvent) => void;
let container!: HTMLElement;
let zoomInHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];
let zoomOutHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];
let resetHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];

export const UldeMermaidBrowserPlugin: BrowserDomPlugin = {
  id: 'browser.mermaid',

  async init(container: HTMLElement) {
    const isBrowser =
      typeof window !== 'undefined' &&
      typeof document !== 'undefined';

    if (!isBrowser) return;



    let mermaidNodes!: NodeListOf<HTMLElement>;

    try {
      // Initialize Mermaid (safe to call multiple times)
      mermaid.initialize({
        startOnLoad: false
      });

      /*
      Source - https://stackoverflow.com/a/79199554
      Posted by grappler
      Retrieved 2026-04-23, License - CC BY-SA 4.0
      */

      // mermaid code block <pre><code class="language-container">...</code></pre> by mardown-it
      const mermaidNodes = container.querySelectorAll<HTMLElement>('.language-mermaid');
      // ctx.logger.info(`onDomInit NodeListOf<HTMLElement>`, mermaidNodes);

      /**
       * A callback to call after each diagram is rendered.
       * mermaid code block: <pre><code class="language-mermaid">'mermaid source'</code></pre>, generated by "markdown-it"
       * this callback changes <pre><code class="language-mermaid"><svg>...</svg></code></pre>to to
       * <pre class="mermaid-container"><div class="mermaid-button-container"><code class="language-mermaid"><svg>...</svg></code></pre>, also to implement zoomIn, zoomOut, reset evens.
       * @param svgId
       * @returns
       */
      const postRenderCB = (svgId: any) => {
        const selectorId = "#" + svgId;
        const svg = container.querySelector(selectorId) as SVGElement;
        if (!svg) return;

        // Initialize Panzoom
        const panzoom = Panzoom(svg as SVGElement, {
          maxScale: 5,
          minScale: 0.5,
          step: 0.1,
        });

        // code node
        const codeNode = svg.parentNode;
        // pre node
        const pre = codeNode?.parentElement;
        if (!pre || !codeNode) return;

        pre.className = "mermaid-container";

        const buttonContainer = document.createElement('div');
        buttonContainer.className = "mermaid-button-container";
        // zoomin
        const zoomIn = document.createElement('button');
        zoomIn.className = "mermaid-zoomin-button";
        zoomIn.innerText = "+";
        const handlerIn = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.zoomIn({ animate: true });
        };
        zoomIn.addEventListener('click', handlerIn);
        zoomInHandlers.push({ button: zoomIn, handler: handlerIn });
        // zoomout
        const zoomOut = document.createElement('button');
        zoomOut.className = "mermaid-zoomout-button";
        zoomOut.innerText = "-";
        const handlerOut = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.zoomOut({ animate: true });
        };
        zoomOut.addEventListener('click', handlerOut);
        zoomOutHandlers.push({ button: zoomOut, handler: handlerOut });
        // rset
        const reset = document.createElement('button');
        reset.className = "mermaid-reset-button";
        reset.innerText = "reset";
        const handlerReset = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.reset({ animate: false });
        };
        reset.addEventListener('click', handlerReset);
        resetHandlers.push({ button: reset, handler: handlerReset });

        buttonContainer.appendChild(zoomIn);
        buttonContainer.appendChild(zoomOut);
        buttonContainer.appendChild(reset);

        pre.insertBefore(buttonContainer, codeNode);

      }

      await mermaid.run({
        nodes: mermaidNodes,
        postRenderCallback: postRenderCB,
      });

    } catch (err) {
      mermaidNodes.forEach(n => console.log(`Log: `, n.children[0].ariaRoleDescription));
      console.error('Error: [ULDE Mermaid Browser Plugin]:', err);
    }
  }
};
