// ulde/plugins/browser/ulde-mermaid-browser.plugin.ts

import { inject } from '@angular/core';
import mermaid, { MermaidConfig } from 'mermaid';
import Panzoom from '@panzoom/panzoom'
import { BrowserDomPlugin } from '../../core/host/ulde-browser-host';
// import { currentTheme } from '../../../global.utils/global.utils';

import { ThemeName, ThemeService } from '../../../core/services/theme.service';

const mermaidConfigDarkTheme: MermaidConfig = {
  startOnLoad: false,
  securityLevel: 'strict',
  theme: 'dark',
  themeVariables: {
    fontSize: '18px',
    fontFamily: 'Trebuchet MS, Verdana, Arial, Sans-Serif',
    primaryColor: '#2d3748',
    primaryTextColor: '#e2e8f0',
    primaryBorderColor: '#63b3ed',
    secondaryColor: '#4a5568',
    tertiaryColor: '#2c5282',
    lineColor: '#63b3ed',
    nodeTextSize: '20px',
    edgeLabelFontSize: '14px',
    labelTextSize: '16px',
    background: '#1e1e1e',
    clusterBkg: '#2d3748',
    clusterBorder: '#63b3ed'
  },
  flowchart: { htmlLabels: true, curve: 'linear' },
  state: { radius: 10 },
  sequence: { noteFontSize: '20px' }
};

const mermaidConfigLightTheme: MermaidConfig = {
  startOnLoad: false,
  securityLevel: 'strict',
  theme: 'default',
  themeVariables: {
    fontSize: '16px',
    fontFamily: 'Trebuchet MS, Verdana, Arial, Sans-Serif',
    primaryColor: '#f0f9ff',
    primaryTextColor: '#1a202c',
    primaryBorderColor: '#3182ce',
    secondaryColor: '#bee3f8',
    tertiaryColor: '#90cdf4',
    lineColor: '#3182ce',
    nodeTextSize: '18px',
    edgeLabelFontSize: '14px',
    labelTextSize: '16px',
    background: '#ffffff',
    clusterBkg: '#edf2f7',
    clusterBorder: '#3182ce'
  },
  flowchart: { htmlLabels: true, curve: 'basis' }
};


let handler!: (event: WheelEvent) => void;
let container!: HTMLElement;
let zoomInHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];
let zoomOutHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];
let resetHandlers: Array<{ button: HTMLButtonElement, handler: (e: Event) => void }> = [];

export const UldeMermaidBrowserPlugin: BrowserDomPlugin = {
  id: 'browser.mermaid',

  async init(container: HTMLElement) {
    const isBrowser =
      typeof window !== 'undefined' &&
      typeof document !== 'undefined';

    if (!isBrowser) return;

    const currentTheme = sessionStorage.getItem('app-theme');
    // const currentTheme = (window as any).__APP_THEME__;
    let mermaidNodes!: NodeListOf<HTMLElement>;

    mermaidNodes = container.querySelectorAll<HTMLElement>('code.language-mermaid');
    // console.log(`Log: [UldeMermaidBrowserPlugin] mermaidNodes=`, mermaidNodes);

    try {

      // mermaid initializing in sync with docTeme;
      mermaid.initialize(currentTheme === 'dark' ? mermaidConfigDarkTheme : mermaidConfigLightTheme);
      // console.log(`Log: [UldeMermaidBrowserPlugin] currentTheme=`, currentTheme);


      /*
      Source - https://stackoverflow.com/a/79199554
      Posted by grappler
      Retrieved 2026-04-23, License - CC BY-SA 4.0
      */

      // mermaid code block <pre><code class="language-container">...</code></pre> by mardown-it


      /**
       * A callback to call after each diagram is rendered.
       * mermaid code block: <pre><code class="language-mermaid">'mermaid source'</code></pre>, generated by "markdown-it"
       * this callback changes <pre><code class="language-mermaid"><svg>...</svg></code></pre>to to
       * <pre class="mermaid-container"><div class="mermaid-button-container"><code class="language-mermaid"><svg>...</svg></code></pre>, also to implement zoomIn, zoomOut, reset evens.
       * @param svgId
       * @returns
       */
      const postRenderCB = (svgId: any) => {
        const selectorId = "#" + svgId;
        const svg = container.querySelector(selectorId) as SVGElement;
        // console.log(`Log: [UldeMermaidBrowserPlugin] svg=`, svg);
        if (!svg) return;

        // Initialize Panzoom
        const panzoom = Panzoom(svg as SVGElement, {
          maxScale: 5,
          minScale: 0.5,
          step: 0.1,
        });

        // code node
        const codeNode = svg.parentNode;
        // pre node
        const pre = codeNode?.parentElement;
        if (!pre || !codeNode) return;

        pre.className = "mermaid-container";

        const buttonContainer = document.createElement('div');
        buttonContainer.className = "mermaid-button-container";
        // zoomin
        const zoomIn = document.createElement('button');
        zoomIn.className = "mermaid-zoomin-button";
        zoomIn.innerText = "+";
        const handlerIn = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.zoomIn({ animate: true });
        };
        zoomIn.addEventListener('click', handlerIn);
        zoomInHandlers.push({ button: zoomIn, handler: handlerIn });
        // zoomout
        const zoomOut = document.createElement('button');
        zoomOut.className = "mermaid-zoomout-button";
        zoomOut.innerText = "-";
        const handlerOut = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.zoomOut({ animate: true });
        };
        zoomOut.addEventListener('click', handlerOut);
        zoomOutHandlers.push({ button: zoomOut, handler: handlerOut });
        // rset
        const reset = document.createElement('button');
        reset.className = "mermaid-reset-button";
        reset.innerText = "reset";
        const handlerReset = (event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          panzoom.reset({ animate: false });
        };
        reset.addEventListener('click', handlerReset);
        resetHandlers.push({ button: reset, handler: handlerReset });

        buttonContainer.appendChild(zoomIn);
        buttonContainer.appendChild(zoomOut);
        buttonContainer.appendChild(reset);

        pre.insertBefore(buttonContainer, codeNode);

        // console.log(`Log: [UldeMermaidBrowserPlugin] final pr=`, pre);

      }

      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          mermaid.run({
            nodes: mermaidNodes,
            postRenderCallback: postRenderCB,
          });
        });
      });
      // await mermaid.run({
      //   nodes: mermaidNodes,
      //   postRenderCallback: postRenderCB,
      // });

    } catch (err) {
      // mermaidNodes.forEach(n => console.log(`Log: `, n.children[0].ariaRoleDescription));
      console.error('Error: [ULDE Mermaid Browser Plugin]:', err);
    }
  }
};
